BaseUrl = "http://opendatask.ca/"
LanguageCode = "en-US"
Title= "Saskatchewan Open Data"
paginate = 5
theme = "hugo-theme-casper"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
DisqusShortname = "open-data-saskatchewan.disqus.com"
Copyright = "All rights reserved - 2021"
canonifyurls = true
publishDir = "picadilly"

[params]
  description = "Data transparency for the flatlands"
  cover = "images/cover.jpg"
  author = "Andrew Dyck"
  authorlocation = "Regina, SK"
  authorwebsite = "http://andrewdyck.com"
  bio= "Andrew loves data. When he's not moving bytes around for analysis or visualization, he's writing about open data."
  logo = "images/logo.png"
  mailchimpurl = "https://opendatask.us20.list-manage.com/subscribe/post?u=4194d641d0e422e7e016b09ba&amp;id=0e854551b7"
  googleAnalyticsUserID = "UA-26754725-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "SaskOpenData"
  twitterName = "opendatask"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "opendatask"


[[menu.main]]
  name = "Home"
  weight = -120
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "About"
  weight = -110
  identifier = "about"
  url = "/about"

[[menu.main]]
  name = "Data Sources"
  weight = -100
  identifier = "data"
  url = "/data"

[[menu.main]]
  name = "Newsletter"
  weight = -90
  identifier = "newsletter"
  url = "/newsletter"

[[menu.main]]
  name = "Contact"
  weight = -80
  identifier = "contact"
  url = "/contact"
